In [1]:
import numpy as np

In [2]:
arr1 = np.array([45,59,65,32])
arr1

array([45, 59, 65, 32])

In [3]:
arr1.shape

(4,)

In [5]:
arr1.ndim

1

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[45,23,56,25],[87,98,45,60],[450,20,15,12]])
arr2

array([[ 45,  23,  56,  25],
       [ 87,  98,  45,  60],
       [450,  20,  15,  12]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.linspace(10,25)

array([10.        , 10.30612245, 10.6122449 , 10.91836735, 11.2244898 ,
       11.53061224, 11.83673469, 12.14285714, 12.44897959, 12.75510204,
       13.06122449, 13.36734694, 13.67346939, 13.97959184, 14.28571429,
       14.59183673, 14.89795918, 15.20408163, 15.51020408, 15.81632653,
       16.12244898, 16.42857143, 16.73469388, 17.04081633, 17.34693878,
       17.65306122, 17.95918367, 18.26530612, 18.57142857, 18.87755102,
       19.18367347, 19.48979592, 19.79591837, 20.10204082, 20.40816327,
       20.71428571, 21.02040816, 21.32653061, 21.63265306, 21.93877551,
       22.24489796, 22.55102041, 22.85714286, 23.16326531, 23.46938776,
       23.7755102 , 24.08163265, 24.3877551 , 24.69387755, 25.        ])

In [13]:
np.linspace(10,25,25,dtype = 'int64')

array([10, 10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20,
       20, 21, 21, 22, 23, 23, 24, 25], dtype=int64)

In [14]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(15) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
np.eye(6) 

array([[2., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 2.]])

In [23]:
arr3 = np.arange(1,101,3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [28]:
arr4 = np.random.randint(45,80)
arr4

71

In [30]:
np.random.seed(1)
arr4 = np.random.randint(45,80,100)
arr4

array([57, 53, 54, 56, 50, 60, 45, 61, 46, 57, 52, 51, 70, 65, 63, 65, 56,
       73, 74, 59, 49, 68, 68, 75, 77, 67, 58, 54, 52, 67, 46, 45, 62, 53,
       69, 58, 53, 75, 52, 48, 51, 66, 48, 49, 69, 57, 71, 61, 63, 60, 45,
       49, 70, 79, 68, 52, 71, 70, 67, 54, 48, 68, 72, 64, 53, 77, 79, 55,
       68, 60, 68, 70, 52, 73, 55, 77, 69, 68, 46, 58, 48, 45, 58, 51, 66,
       51, 47, 57, 72, 66, 56, 52, 58, 53, 56, 57, 65, 75, 52, 49])

In [31]:
arr4 = arr4.reshape(10,10)
arr4

array([[57, 53, 54, 56, 50, 60, 45, 61, 46, 57],
       [52, 51, 70, 65, 63, 65, 56, 73, 74, 59],
       [49, 68, 68, 75, 77, 67, 58, 54, 52, 67],
       [46, 45, 62, 53, 69, 58, 53, 75, 52, 48],
       [51, 66, 48, 49, 69, 57, 71, 61, 63, 60],
       [45, 49, 70, 79, 68, 52, 71, 70, 67, 54],
       [48, 68, 72, 64, 53, 77, 79, 55, 68, 60],
       [68, 70, 52, 73, 55, 77, 69, 68, 46, 58],
       [48, 45, 58, 51, 66, 51, 47, 57, 72, 66],
       [56, 52, 58, 53, 56, 57, 65, 75, 52, 49]])

In [32]:
arr4[4,5]

57

In [33]:
arr4[3:8,3:8]

array([[53, 69, 58, 53, 75],
       [49, 69, 57, 71, 61],
       [79, 68, 52, 71, 70],
       [64, 53, 77, 79, 55],
       [73, 55, 77, 69, 68]])

In [34]:
arr4[3:8,3:8] = 50
arr4

array([[57, 53, 54, 56, 50, 60, 45, 61, 46, 57],
       [52, 51, 70, 65, 63, 65, 56, 73, 74, 59],
       [49, 68, 68, 75, 77, 67, 58, 54, 52, 67],
       [46, 45, 62, 50, 50, 50, 50, 50, 52, 48],
       [51, 66, 48, 50, 50, 50, 50, 50, 63, 60],
       [45, 49, 70, 50, 50, 50, 50, 50, 67, 54],
       [48, 68, 72, 50, 50, 50, 50, 50, 68, 60],
       [68, 70, 52, 50, 50, 50, 50, 50, 46, 58],
       [48, 45, 58, 51, 66, 51, 47, 57, 72, 66],
       [56, 52, 58, 53, 56, 57, 65, 75, 52, 49]])

In [35]:
arr4.flatten()

array([57, 53, 54, 56, 50, 60, 45, 61, 46, 57, 52, 51, 70, 65, 63, 65, 56,
       73, 74, 59, 49, 68, 68, 75, 77, 67, 58, 54, 52, 67, 46, 45, 62, 50,
       50, 50, 50, 50, 52, 48, 51, 66, 48, 50, 50, 50, 50, 50, 63, 60, 45,
       49, 70, 50, 50, 50, 50, 50, 67, 54, 48, 68, 72, 50, 50, 50, 50, 50,
       68, 60, 68, 70, 52, 50, 50, 50, 50, 50, 46, 58, 48, 45, 58, 51, 66,
       51, 47, 57, 72, 66, 56, 52, 58, 53, 56, 57, 65, 75, 52, 49])

In [37]:
arr4[arr4>50]

array([57, 53, 54, 56, 60, 61, 57, 52, 51, 70, 65, 63, 65, 56, 73, 74, 59,
       68, 68, 75, 77, 67, 58, 54, 52, 67, 62, 52, 51, 66, 63, 60, 70, 67,
       54, 68, 72, 68, 60, 68, 70, 52, 58, 58, 51, 66, 51, 57, 72, 66, 56,
       52, 58, 53, 56, 57, 65, 75, 52])

In [38]:
arr4[arr4 == 50]

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50])

In [39]:
np.sum(arr4)

5622

In [40]:
np.mean(arr4)

56.22

In [41]:
np.median(arr4)

52.0

In [42]:
np.std(arr4)

8.463545356409451

In [43]:
np.var(arr4)

71.63159999999999

In [44]:
np.sqrt(arr4)

array([[7.54983444, 7.28010989, 7.34846923, 7.48331477, 7.07106781,
        7.74596669, 6.70820393, 7.81024968, 6.78232998, 7.54983444],
       [7.21110255, 7.14142843, 8.36660027, 8.06225775, 7.93725393,
        8.06225775, 7.48331477, 8.54400375, 8.60232527, 7.68114575],
       [7.        , 8.24621125, 8.24621125, 8.66025404, 8.77496439,
        8.18535277, 7.61577311, 7.34846923, 7.21110255, 8.18535277],
       [6.78232998, 6.70820393, 7.87400787, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 7.21110255, 6.92820323],
       [7.14142843, 8.1240384 , 6.92820323, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 7.93725393, 7.74596669],
       [6.70820393, 7.        , 8.36660027, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 8.18535277, 7.34846923],
       [6.92820323, 8.24621125, 8.48528137, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 8.24621125, 7.74596669],
       [8.24621125, 8.36660027, 7.2111025

In [45]:
np.max(arr4)

77

In [46]:
np.min(arr4)

45

In [47]:
np.argmax(arr4)

24

In [48]:
np.argmin(arr4)

6

In [49]:
np.percentile(arr4,20)

50.0

In [50]:
np.percentile(arr4,75)

63.0

In [51]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [ ]:
#Generate a random array between 50 and 105 consisting of 400 values reshape this to equal rows and columns
#retrive the values from the 5th to 10th row and 7th to 15th colums
#write a condition to retrive values >= 70
#return the output of the following operations
#sum of the array, max value, min value, 25,80,85,90,95 percentile

In [53]:
import pandas as pd
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [54]:
fruits = ['Apple','Cherry','Lemon','Grape']
values = [400,50,205,156]
s1 = pd.Series(data = values,index = fruits)
s1

Apple     400
Cherry     50
Lemon     205
Grape     156
dtype: int64

In [55]:
s1['Cherry']

50

In [56]:
s2 = pd.Series(data = values)
s2

0    400
1     50
2    205
3    156
dtype: int64