In [1]:
import numpy as np
import pandas as pd

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [3]:
arr1 = np.array([45,58,98,98])

In [4]:
arr1.ndim

1

In [5]:
arr1.shape

(4,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[45,89,87],[45,65,98]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 3)

In [10]:
np.linspace(20,50)

array([20.        , 20.6122449 , 21.2244898 , 21.83673469, 22.44897959,
       23.06122449, 23.67346939, 24.28571429, 24.89795918, 25.51020408,
       26.12244898, 26.73469388, 27.34693878, 27.95918367, 28.57142857,
       29.18367347, 29.79591837, 30.40816327, 31.02040816, 31.63265306,
       32.24489796, 32.85714286, 33.46938776, 34.08163265, 34.69387755,
       35.30612245, 35.91836735, 36.53061224, 37.14285714, 37.75510204,
       38.36734694, 38.97959184, 39.59183673, 40.20408163, 40.81632653,
       41.42857143, 42.04081633, 42.65306122, 43.26530612, 43.87755102,
       44.48979592, 45.10204082, 45.71428571, 46.32653061, 46.93877551,
       47.55102041, 48.16326531, 48.7755102 , 49.3877551 , 50.        ])

In [11]:
np.linspace(20,50,10)

array([20.        , 23.33333333, 26.66666667, 30.        , 33.33333333,
       36.66666667, 40.        , 43.33333333, 46.66666667, 50.        ])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5) *4

array([4., 4., 4., 4., 4.])

In [16]:
arr3 = np.eye(6)
arr3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
arr3 = arr3.flatten()
arr3

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [19]:
arr4 = np.arange(1,101)
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [20]:
arr4 = np.arange(1,101,3)
arr4

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [22]:
arr5 = np.random.randint(25,65)
arr5

48

In [23]:
arr5 = np.random.randint(25,65,100)
arr5

array([54, 63, 54, 37, 39, 43, 51, 27, 46, 42, 43, 25, 40, 32, 35, 58, 59,
       55, 50, 27, 53, 30, 55, 41, 31, 50, 34, 43, 50, 27, 26, 48, 36, 55,
       55, 62, 55, 42, 45, 59, 25, 32, 30, 33, 41, 27, 59, 63, 36, 40, 59,
       44, 54, 63, 59, 63, 52, 26, 34, 42, 32, 60, 35, 62, 59, 56, 47, 28,
       40, 46, 57, 27, 33, 54, 46, 38, 31, 62, 60, 37, 36, 35, 41, 38, 49,
       55, 46, 57, 49, 28, 36, 39, 26, 41, 25, 47, 47, 41, 28, 46])

In [24]:
arr5 = arr5.reshape(10,10)
arr5

array([[54, 63, 54, 37, 39, 43, 51, 27, 46, 42],
       [43, 25, 40, 32, 35, 58, 59, 55, 50, 27],
       [53, 30, 55, 41, 31, 50, 34, 43, 50, 27],
       [26, 48, 36, 55, 55, 62, 55, 42, 45, 59],
       [25, 32, 30, 33, 41, 27, 59, 63, 36, 40],
       [59, 44, 54, 63, 59, 63, 52, 26, 34, 42],
       [32, 60, 35, 62, 59, 56, 47, 28, 40, 46],
       [57, 27, 33, 54, 46, 38, 31, 62, 60, 37],
       [36, 35, 41, 38, 49, 55, 46, 57, 49, 28],
       [36, 39, 26, 41, 25, 47, 47, 41, 28, 46]])

In [25]:
arr5[4,4]

41

In [26]:
arr5[4:7,2:5]

array([[30, 33, 41],
       [54, 63, 59],
       [35, 62, 59]])

In [27]:
arr5[4:7,2:5] = 27
arr5

array([[54, 63, 54, 37, 39, 43, 51, 27, 46, 42],
       [43, 25, 40, 32, 35, 58, 59, 55, 50, 27],
       [53, 30, 55, 41, 31, 50, 34, 43, 50, 27],
       [26, 48, 36, 55, 55, 62, 55, 42, 45, 59],
       [25, 32, 27, 27, 27, 27, 59, 63, 36, 40],
       [59, 44, 27, 27, 27, 63, 52, 26, 34, 42],
       [32, 60, 27, 27, 27, 56, 47, 28, 40, 46],
       [57, 27, 33, 54, 46, 38, 31, 62, 60, 37],
       [36, 35, 41, 38, 49, 55, 46, 57, 49, 28],
       [36, 39, 26, 41, 25, 47, 47, 41, 28, 46]])

In [28]:
np.sum(arr5)

4186

In [29]:
np.mean(arr5)

41.86

In [31]:
np.percentile(arr5,50)

41.0

In [32]:
np.median(arr5)

41.0

In [33]:
df =pd.read_csv('sample_pivot.csv')
df.head()

Date Region                 Type  Units  Sales
0  7/11/2020   East  Children's Clothing   18.0    306
1  9/23/2020  North  Children's Clothing   14.0    448
2   4/2/2020  South     Women's Clothing   17.0    425
3  2/28/2020   East  Children's Clothing   26.0    832
4  3/19/2020   West     Women's Clothing    3.0     33

In [34]:
df.tail()

Date Region                 Type  Units  Sales
995   2/11/2020   East  Children's Clothing   35.0    735
996  12/25/2020  North       Men's Clothing    NaN   1155
997   8/31/2020  South       Men's Clothing   13.0    208
998   8/23/2020  South     Women's Clothing   17.0    493
999   8/17/2020  North     Women's Clothing   25.0    300

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1000 non-null   object 
 1   Region  1000 non-null   object 
 2   Type    1000 non-null   object 
 3   Units   911 non-null    float64
 4   Sales   1000 non-null   int64  
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB


In [36]:
df.isnull().sum()

Date       0
Region     0
Type       0
Units     89
Sales      0
dtype: int64

In [37]:
df2  = df.copy()

In [38]:
df2.dropna(inplace=True)

In [39]:
df2.shape

(911, 5)

In [40]:
df.shape

(1000, 5)

In [41]:
df['Units'].fillna(0,inplace =True)

In [42]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    1000 non-null   datetime64[ns]
 1   Region  1000 non-null   object        
 2   Type    1000 non-null   object        
 3   Units   1000 non-null   float64       
 4   Sales   1000 non-null   int64         
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 39.2+ KB
